language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-27.0.3
  - android-27
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
jdk:
- oraclejdk8
before_install:
- yes | sdkmanager "platforms;android-27"
script:
- '[[ "${TRAVIS_PULL_REQUEST}" == "false" ]] && ./gradlew assembleRelease || ./gradlew assembleDebug'
before_deploy:
- '[[ "${TRAVIS_PULL_REQUEST}" == "false" ]] && mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/MinMinGuard.apk'
deploy:
  provider: releases
  api_key:
    secure: SyXfTosXZAJbm3lX1ZTJLlsPwWpf3GVUqYS5PTpjwp0wSKd5/eE4+/nDPNm0hmzjZ49ur8Z0ys3vHV9a4mSaawkWrHuxQAsbEut4AdOduicnSHyQgnlnFuMkpdAdSU4Rfw83RuvH7j4R8SKhwemI1xIHAOdAfA8icqAtLR/m+dkPkjfVPMyL5LBm8QsAgbUBhlZTFDoAkTfPP9qfW31HQvVLiK6w2GYVYcDfi+dAFf5zt2CtQ/b1f5RPpu1FeQZpptqhtSuh/pYE2ux6vLWOXSsZP14OKZxhA9Xu4xIAV/8MTF5lLJUP8VKBUgz3G2SZIbEf4YtLCKQPFn8fy8KAP/TFe83c6poTnqFxoZUuHF0os+dC+/xIyMVlvi2gUWNsM6D4I0fjDntv+c4OxPyTqqtIIfZUXMbLfofzMY5XXQyBRKZAFcir+HR396J7OCKPX8QqBIQV8zpgXEmhufUwPSwDQkcW3muss9cunAuThecc12oaaqrNbqay1gF55ykbZjL2OgREXda8uVZrGr8oy4+Pdn63Ehr1tBOhd2hfuVMfP8W81LBHaeGVbRqrnEAGTx6sm647103XyYDufD6g9VHxHhrsNZCaHlT/wYGD2TwYP5brJKW5LwGduC+qdgXUyzSWAFkLedxbSlWR6oVdduCEiuR7XVdzAegIn0hMwsk=
  file: app/build/outputs/apk/release/MinMinGuard.apk
  skip_cleanup: true
  on:
    tags: true
    repo: chiehmin/MinMinGuard
